packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@stellar/stellar-sdk': false
  blake-hash: false
  bufferutil: false
  esbuild: true
  prisma: true
  protobufjs: false
  sharp: true
  tiny-secp256k1: false
  usb: false
  utf-8-validate: false
